# Generated by Django 4.2.13 on 2024-06-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works365', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('1', 'Limpeza'), ('2', 'Reparos'), ('3', 'Consultoria'), ('4', 'Outros')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Professional',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
